-- NFT 프로젝트

-- 회원별 경매내역 보기 프로시저
-- 경매번호, 회원아이디, p.그림명, 낙찰가, 경매종료시간
-- auction 테이블의 회원아이디로 검색
CREATE OR REPLACE PROCEDURE PRO_USER_AUC_LIST
(
  presult out sys_refcursor,
  in_userId IN VARCHAR2
)
IS
BEGIN
  open presult for

  SELECT A.AUC_NO, U.USER_ID, P.PRO_NAME, A.AUC_LPRICE, TO_CHAR(A.AUC_END)
         FROM T_AUCTION A, USER_T  U, PRODUCT_T  P
      WHERE A.USER_NO = U.USER_NO
        AND A.PRO_NO = P.PRO_NO
        AND U.USER_ID like in_userId;
END PRO_USER_AUC_LIST;
/

-- 프로시저 실행
variable rc refcursor;
variable uid varchar2;
execute PRO_USER_AUC_LIST(:rc, 'TESTus%');
print rc;


-- 회원 고유번호 증가 시퀀스
CREATE SEQUENCE SEQ_T_USER_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  NOCYCLE
  CACHE 2;

-- 회원테이블
CREATE TABLE T_USER (
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(100),
  USER_PASS VARCHAR2(20),
  USER_BIR date,
  USER_NICK VARCHAR2(20),
  USER_CREDAY DATE,
  WAL_NO NUMBER,
  USER_ICON BLOB
);

-- 회원 데이터
INSERT INTO T_USER VALUES (SEQ_T_USER_NO.NEXTVAL, 'test1', '1234', TO_DATE('1972-06-29', 'YYYY/MM/DD'), '세종', TO_DATE('2022-06-01', 'YYYY/MM/DD'), 1111,  NULL);
INSERT INTO T_USER VALUES (SEQ_T_USER_NO.NEXTVAL, 'test2', '2234', TO_DATE('1970-02-15', 'YYYY/MM/DD'), '태조', TO_DATE('2022-06-05', 'YYYY/MM/DD'), 2222, NULL);
INSERT INTO T_USER VALUES (SEQ_T_USER_NO.NEXTVAL, 'TESTuser', '1234', TO_DATE('1972-06-29', 'YYYY/MM/DD'), '테스트유저', TO_DATE('2022-06-01', 'YYYY/MM/DD'), 3333, NULL);
INSERT INTO T_USER VALUES (SEQ_T_USER_NO.NEXTVAL, 'TESTuser2', '2234', TO_DATE('1970-02-15', 'YYYY/MM/DD'), '테스트유저2', TO_DATE('2022-06-05', 'YYYY/MM/DD'), 4444, NULL);
INSERT INTO T_USER VALUES (SEQ_T_USER_NO.NEXTVAL, 'ASD', '3234', TO_DATE('1987-01-25', 'YYYY/MM/DD'), '임시유저', TO_DATE('2022-06-06', 'YYYY/MM/DD'), 5555, NULL);

-- 그림(상품) 고유번호 증가 시퀀스
CREATE SEQUENCE SEQ_T_PRO_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  NOCYCLE
  CACHE 2;

-- 그림(상품) 테이블
-- 상품고유번호, 회원고유번호, 상품명, 상품가격, 상품설명, 등록일, 상품이미지, 상품이미지번호(?) 
CREATE TABLE T_PRODUCT (
  PRO_NO NUMBER PRIMARY KEY,
  USER_NO NUMBER,
  PRO_NAME VARCHAR2(100),
  PRO_PRICE NUMBER,
  PRO_EXP VARCHAR2(100),
  PRO_REGDAY DATE,
  PRO_IMG BLOB,
  PRO_IMG_SIGNED BLOB
);

-- 그림 데이터
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 1, '01_theMonaLisa', 100, 'The MonaLisa', TO_DATE('2022-06-01', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 1, '02_theLastSupper', 100, 'the Last Supper', TO_DATE('2022-06-01', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 2, '03_theStarryNight', 100, 'The Starry Night', TO_DATE('2022-06-03', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 3, '04_theScream', 100, 'The Scream',TO_DATE('2022-06-03', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 3, '05_guernica', 100, 'Guernica',TO_DATE('2022-06-04', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 2, '06_theKiss', 100, 'The Kiss', TO_DATE('2022-06-04', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 2, '07_theGirlWithaPearlEarring', 100, 'The Girl With a Pearl Earring', TO_DATE('2022-06-05', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 1, '08_theBirth0fVenus', 100, 'The Birth 0f Venus', TO_DATE('2022-06-01', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 4, '09_LasMeninas', 100, 'Las Meninas', TO_DATE('2022-06-06', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 4, '10_theCreationOfAdam', 100, 'The Creation Of Adam', TO_DATE('2022-06-06', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 5, '11_americanGothic', 100, 'American Gothic', TO_DATE('2022-06-06', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 6, '12_LeMatinAuxSaules', 100, 'Le Matin Aux Saules', TO_DATE('2022-06-07', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 6,'13_thePersistenceOfMemory', 100, 'The Persistence Of Memory', TO_DATE('2022-06-10', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 7, '14_theNightwatch', 100, 'The Nightwatch', TO_DATE('2022-06-10', 'YYYY/MM/DD'), NULL, NULL);
INSERT INTO T_PRODUCT VALUES (SEQ_T_PRO_NO.NEXTVAL, 2, '15_theGardenOfEarthlyDelights', 100, 'The Garden Of Earthly Delights', TO_DATE('2022-06-11', 'YYYY/MM/DD'), NULL, NULL);

-- 경매 고유번호 증가 시퀀스
CREATE SEQUENCE SEQ_T_AUC_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  NOCYCLE
  CACHE 2;
  
-- 경매 테이블
-- 경매 고유번호, 상품 고유번호, 최초가격, 낙찰가,
-- 등록일, 경매 시작시간, 경매 종료시간, 낙찰받은 회원 고유번호
CREATE TABLE T_AUCTION (
  AUC_NO NUMBER PRIMARY KEY,
  PRO_NO NUMBER,
  AUC_FPRICE NUMBER,
  AUC_LPRICE NUMBER,
  PRO_REGDAY DATE,
  AUC_START DATE,
  AUC_END DATE,
  USER_NO NUMBER
);

-- 경매 데이터
INSERT INTO T_AUCTION VALUES (SEQ_T_AUC_NO.NEXTVAL, 1, 1000, 250000, TO_DATE('2022-06-03', 'YYYY/MM/DD'), 
  TO_DATE('2022-06-03 09:00:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-03 09:30:00', 'YYYY/MM/DD HH24:MI:SS'), 1);
INSERT INTO T_AUCTION VALUES (SEQ_T_AUC_NO.NEXTVAL, 2, 1000, 5760000, TO_DATE('2022-06-06', 'YYYY/MM/DD'), 
  TO_DATE('2022-06-06 12:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-06 15:00:00', 'YYYY/MM/DD HH24:MI:SS'), 2);
INSERT INTO T_AUCTION VALUES (SEQ_T_AUC_NO.NEXTVAL, 7, 1000, 9990000, TO_DATE('2022-09-09', 'YYYY/MM/DD'), 
    TO_DATE('2022-09-10 12:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-29 15:00:00', 'YYYY/MM/DD HH24:MI:SS'), 2);
INSERT INTO T_AUCTION VALUES (SEQ_T_AUC_NO.NEXTVAL, 8, 1000, 9990000, TO_DATE('2022-09-09', 'YYYY/MM/DD'), 
    TO_DATE('2022-09-10 16:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-09-10 17:00:00', 'YYYY/MM/DD HH24:MI:SS'), 2);
INSERT INTO T_AUCTION VALUES (SEQ_T_AUC_NO.NEXTVAL, 5, 2000, 5200000, TO_DATE('2022-09-09', 'YYYY/MM/DD'), 
    TO_DATE('2022-06-30 16:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-30 12:00:00', 'YYYY/MM/DD HH24:MI:SS'), 3);
INSERT INTO T_AUCTION VALUES (SEQ_T_AUC_NO.NEXTVAL, 6, 2000, 9200000, TO_DATE('2022-05-09', 'YYYY/MM/DD'), 
    TO_DATE('2022-06-30 16:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-30 18:00:00', 'YYYY/MM/DD HH24:MI:SS'), 3);

update T_AUCTION set AUC_END = sysdate where auc_NO = 6;
update T_AUCTION set AUC_END = sysdate where auc_NO = 5;
update T_AUCTION set AUC_END = sysdate where auc_NO = 4;


-- 경매로그 고유번호 증가 시퀀스
CREATE SEQUENCE SEQ_T_AUC_LOG_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  NOCYCLE
  CACHE 2;
  
CREATE TABLE T_AUCTION_LOG (
  AUG_LOG_NO NUMBER PRIMARY KEY,
  AUC_NO NUMBER,
  USER_NO NUMBER,
  AUC_AMOUNT NUMBER,
  AUC_SUCCESS_YN CHAR(1),
  AUC_LOG_DATE DATE
);

INSERT INTO T_AUCTION_LOG VALUES (SEQ_T_AUC_LOG_NO.NEXTVAL, 1, 1, 100, 'Y', SYSDATE);
INSERT INTO T_AUCTION_LOG VALUES (SEQ_T_AUC_LOG_NO.NEXTVAL, 1, 2, 90, 'N', SYSDATE);

-- 전자지갑 테이블
CREATE TABLE T_WALLET(
    WAL_NO NUMBER PRIMARY KEY,
    WAL_NAME VARCHAR(20), 
    WAL_AMOUNT NUMBER
);

insert into t_wallet values(1111, '모승범', 100000);
insert into t_wallet values(2222, '정의영', 100000);
insert into t_wallet values(3333, '신서아', 100000);
insert into t_wallet values(4444, '이태우', 100000);
insert into t_wallet values(5555, '조정욱', 100000);
insert into t_wallet values(7777, '김보미', 100000);
insert into t_wallet values(9999, 'VFT', 100000);

-- 전자지갑로그
CREATE SEQUENCE SEQ_T_WAL_LOG_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  NOCYCLE
  CACHE 2;
  
create table T_WALLET_LOG(
    WAL_LOG_NO number PRIMARY KEY,
    FROM_WAL_NO number,
    TO_WAL_NO number,
    AMOUNT number,
    LOG_TIME date
);

insert into T_WALLET_LOG values(SEQ_T_WAL_LOG_NO.NEXTVAL, 1111, 2222, 10, sysdate);
insert into T_WALLET_LOG values(SEQ_T_WAL_LOG_NO.NEXTVAL, 1111, 2222, 30, sysdate);

SELECT * FROM T_USER;
SELECT * FROM T_PRODUCT;
SELECT * FROM T_AUCTION;
SELECT * FROM T_AUCTION_LOG;
SELECT * FROM T_WALLET;
SELECT * FROM T_WALLET_LOG;

drop SEQUENCE SEQ_INCREASE_USER_NO;
drop SEQUENCE SEQ_INCREASE_PRO_NO;
drop SEQUENCE SEQ_INCREASE_AUC_NO;



-- 기존 작업하던 테이블과 데이터 -----------------------------------------------
-- 팀프로젝트 
-- 상품 테이블

-- 회원 고유번호 증가 시퀀스
CREATE SEQUENCE SEQ_INCREASE_USER_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  NOCYCLE
  CACHE 2;

-- 회원테이블  
-- 고유번호,아이디,비번,생일,닉네임,가입일,아이콘
CREATE TABLE USER_T (
  USER_NO NUMBER NOT NULL,
  USER_ID VARCHAR2(100),
  USER_PASS VARCHAR2(20),
  USER_BIR date,
  USER_NICK VARCHAR2(20),
  USER_CREDAY DATE,
  USER_ICON BLOB
);

INSERT INTO USER_T VALUES (SEQ_INCREASE_USER_NO.NEXTVAL, 'TESTuser', '1234', TO_DATE('1972-06-29', 'YYYY/MM/DD'), '테스트유저', TO_DATE('2022-06-01', 'YYYY/MM/DD'), NULL);
INSERT INTO USER_T VALUES (SEQ_INCREASE_USER_NO.NEXTVAL, 'TESTuser2', '2234', TO_DATE('1970-02-15', 'YYYY/MM/DD'), '테스트유저2', TO_DATE('2022-06-05', 'YYYY/MM/DD'), NULL);
INSERT INTO USER_T VALUES (SEQ_INCREASE_USER_NO.NEXTVAL, 'ASD', '3234', TO_DATE('1987-01-25', 'YYYY/MM/DD'), '임시유저', TO_DATE('2022-06-06', 'YYYY/MM/DD'), NULL);


-- 그림 상품 테이블
-- 기존 수업 테이블과 중복으로 PRODUCT_T 로 작업함
-- 가격은 NULL 값으로 기본

-- 상품 고유번호 증가 시퀀스
CREATE SEQUENCE SEQ_INCREASE_PRO_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  NOCYCLE
  CACHE 2;
  
-- 그림 상품테이블
-- 상품고유번호, 회원고유번호, 상품명, 상품가격, 상품설명, 등록일  
CREATE TABLE PRODUCT_T(
  PRO_NO NUMBER NOT NULL,
  USER_NO NUMBER,
  PRO_NAME VARCHAR2(100),
  PRO_PRICE NUMBER,
  PRO_EXP VARCHAR2(100),
  PRO_REGDAY DATE
);
INSERT INTO PRODUCT_T VALUES (SEQ_INCREASE_PRO_NO.NEXTVAL, 1, 'theMonaLisa', NULL, 
                                'The MonaLisa', TO_DATE('2022-06-03', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_T VALUES (SEQ_INCREASE_PRO_NO.NEXTVAL, 1, 'theLastSupper', NULL, 
                                'the Last Supper', TO_DATE('2022-06-03', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_T VALUES (SEQ_INCREASE_PRO_NO.NEXTVAL, 2, 'theStarryNight', NULL, 
                                'The Starry Night', TO_DATE('2022-06-06', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_T VALUES (SEQ_INCREASE_PRO_NO.NEXTVAL, 3, 'theScream', NULL, 
                                 'The Scream', TO_DATE('2022-09-09', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_T VALUES (SEQ_INCREASE_PRO_NO.NEXTVAL, 3, 'guernica',  NULL, 
                                'Guernica', TO_DATE('2022-05-09', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_T VALUES (SEQ_INCREASE_PRO_NO.NEXTVAL, 2, 'theKiss',  NULL, 
                                'The Kiss', TO_DATE('2022-09-10', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_T VALUES (SEQ_INCREASE_PRO_NO.NEXTVAL, 2, 'theGirlWithaPearlEarring', NULL, 
                                'The Girl With a Pearl Earring', TO_DATE('2022-09-09', 'YYYY/MM/DD'));
SELECT * FROM PRODUCT_T;


-- 경매 고유번호 증가 시퀀스
CREATE SEQUENCE SEQ_INCREASE_AUC_NO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 0
  NOCYCLE
  CACHE 2;
  
-- 경매내역 테이블
-- 경매 고유번호, 상품 고유번호, 최초가격,
-- 낙찰가, 등록일, 경매 시작시간, 경매 종료시간, 관리자 아이디, 낙찰받은 회원 고유번호
CREATE TABLE AUCTION (
  AUC_NO NUMBER NOT NULL,
  PRO_NO NUMBER,
  AUC_FPRICE NUMBER,
  AUC_LPRICE NUMBER,
  PRO_REGDAY DATE,
  AUC_START DATE,
  AUC_END DATE,
  USER_NO NUMBER
);

INSERT INTO AUCTION VALUES (SEQ_INCREASE_AUC_NO.NEXTVAL, 1, 1000, 250000, TO_DATE('2022-06-03', 'YYYY/MM/DD'), 
    TO_DATE('2022-06-03 09:00:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-03 09:30:00', 'YYYY/MM/DD HH24:MI:SS'), 1);
INSERT INTO AUCTION VALUES (SEQ_INCREASE_AUC_NO.NEXTVAL, 2, 1000, 5760000, TO_DATE('2022-06-06', 'YYYY/MM/DD'), 
    TO_DATE('2022-06-06 12:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-06 15:00:00', 'YYYY/MM/DD HH24:MI:SS'), 2);
INSERT INTO AUCTION VALUES (SEQ_INCREASE_AUC_NO.NEXTVAL, 99, 1000, 9990000, TO_DATE('2022-09-09', 'YYYY/MM/DD'), 
    TO_DATE('2022-09-10 12:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-29 15:00:00', 'YYYY/MM/DD HH24:MI:SS'), 2);
INSERT INTO AUCTION VALUES (SEQ_INCREASE_AUC_NO.NEXTVAL, 999, 1000, 9990000, TO_DATE('2022-09-09', 'YYYY/MM/DD'), 
    TO_DATE('2022-09-10 16:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-09-10 17:00:00', 'YYYY/MM/DD HH24:MI:SS'), 2);
INSERT INTO AUCTION VALUES (SEQ_INCREASE_AUC_NO.NEXTVAL, 98, 2000, 5200000, TO_DATE('2022-09-09', 'YYYY/MM/DD'), 
    TO_DATE('2022-06-30 16:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-30 12:00:00', 'YYYY/MM/DD HH24:MI:SS'), 3);
INSERT INTO AUCTION VALUES (SEQ_INCREASE_AUC_NO.NEXTVAL, 97, 2000, 9200000, TO_DATE('2022-05-09', 'YYYY/MM/DD'), 
    TO_DATE('2022-06-30 16:30:00', 'YYYY/MM/DD HH24:MI:SS'), TO_DATE('2022-06-30 18:00:00', 'YYYY/MM/DD HH24:MI:SS'), 3);

SELECT * FROM AUCTION;
--update auction set AUC_END = sysdate where PRO_NO = 99;
update auction set AUC_END = sysdate where auc_NO = 6;
update auction set AUC_END = sysdate where auc_NO = 5;
update auction set AUC_END = sysdate where auc_NO = 4;

-- 오늘날짜의 경매건수 검색
SELECT COUNT(*) FROM AUCTION WHERE SUBSTR(TO_CHAR(AUC_START), 1, 10) = TO_CHAR(SYSDATE);

-- 오늘날짜의 경매금액 합계
SELECT sum(AUC_LPRICE) FROM AUCTION WHERE SUBSTR(TO_CHAR(AUC_END), 1, 10) = TO_CHAR(SYSDATE);



-- 낙찰경매 리스트 가져오기
-- 경매번호, 상품번호, 낙찰자 닉네임(A)
SELECT A.AUC_NO, A.PRO_NO, P.PRO_NAME, U.USER_ID FROM AUCTION A, USER_T U, PRODUCT_T P WHERE A.USER_NO = U.USER_NO AND A.PRO_NO = P.PRO_NO;



CREATE TABLE WALLET(
  WAL_NO NUMBER CONSTRAINT WAL_NO_PK PRIMARY KEY,
  WAL_NAME VARCHAR(20)
);
select*from point;
insert into wallet values(1,'정의영'); --테스트
insert into wallet values(2,'모승범'); --테스트

create table point(
  pnt_no number,
  user_id varchar2(100),      --변경함
  pnt_total number,
  pnt_in  number,
  pnt_out  number,
  pnt_day date
);

insert into point values(1,2,3,4,5,sysdate);  --테스트












-- 기존 작업용 임시 테이블과 쿼리

INSERT INTO PRODUCT_B VALUES (1, '01_theMonaLisa', 'The MonaLisa', null, 01, TO_DATE('2022-06-01', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (2, '02_theLastSupper', 'the Last Supper', null, 01, TO_DATE('2022-06-01', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (3, '03_theStarryNight', 'The Starry Night', null, 02, TO_DATE('2022-06-03', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (4, '04_theScream', 'The Scream', null, 02, TO_DATE('2022-06-03', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (5, '05_guernica', 'Guernica', null, 03, TO_DATE('2022-06-04', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (6, '06_theKiss', 'The Kiss', null, 03, TO_DATE('2022-06-04', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (7, '07_theGirlWithaPearlEarring', 'The Girl With a Pearl Earring', null, 03, TO_DATE('2022-06-05', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (8, '08_theBirth0fVenus', 'The Birth 0f Venus', null, 04, TO_DATE('2022-06-01', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (9, '09_LasMeninas', 'Las Meninas', null, 04, TO_DATE('2022-06-06', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (10, '10_theCreationOfAdam', 'The Creation Of Adam', null, 05, TO_DATE('2022-06-06', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (11, '11_americanGothic', 'American Gothic', null, 05, TO_DATE('2022-06-06', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (12, '12_LeMatinAuxSaules', 'Le Matin Aux Saules', null, 06, TO_DATE('2022-06-07', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (13, '13_thePersistenceOfMemory', 'The Persistence Of Memory', null, 07, TO_DATE('2022-06-10', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (14, '14_theNightwatch', 'The Nightwatch', null, 07, TO_DATE('2022-06-10', 'YYYY/MM/DD'));
INSERT INTO PRODUCT_B VALUES (15, '15_theGardenOfEarthlyDelights', 'The Garden Of Earthly Delights', null, 07, TO_DATE('2022-06-11', 'YYYY/MM/DD'));

